### ISSUE TITLE
endpoint-trait TODO list

### ISSUE THREAD

**Issue by mvirkkunen** [mvirkkunen/usb-device#38]
These need to be done before it's finished:

- [x] Better getter for string descriptors (maybe even put them in configure, it may waste a few cycles, but it's not like they're requested often)
- [x] Implement GET_INTERFACE properly
- [x] Make TestClass use the state parameter passed in to poll() now
- [x] Add an EndpointIn/EndpointOut method to check if they're enabled (maybe superfluous since there's alt_setting_activated?)
- [x] Add an EndpointIn::flush() method
- [x] Maybe change the way endpoints are referred to in endpoint_out/endpoint_in_complete? Add an EndpointSet type with fn contains(ep: &Endpoint) which checks both address and enabled state
- [x] Document all the things
- [x] Add support for extra bytes to endpoint descriptors (weird USB Audio spec)
- [x] Add support for interface names to interface descriptor
- [x] Add `PartialEq` methods between `InterfaceHandle` and friends and `u8` (and maybe `u16`)
- [x] (stm32-usbd) Make the endpoint index returned from allocations an unsafe-to-create type that can be used for offsets without bounds checks later
